name: Daily Country Crawler

on:
  schedule:
    - cron: '0 12 * * *'  # 每天中午 12:00 (UTC)，台灣時間 20:00
  workflow_dispatch:      # 手動觸發支援

jobs:
  run-crawlers:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests

    - name: Run static.py
      run: python static.py

    - name: Run api.py
      run: python api.py

    - name: Upload CSV results
      uses: actions/upload-artifact@v3
      with:
        name: crawler-results
        path: |
          static.csv
          static.json
          api.csv
